"""Agent access matrix and tool catalog."""
from __future__ import annotations

AGENT_TOOL_ACCESS: dict[str, set[str]] = {
    "bea-architect": {
        "tool_read_file", "tool_list_directory", "tool_detect_file_dependencies",
        "tool_syntax_validate", "tool_import_graph", "tool_circular_import_detect",
        "tool_dead_code_detect", "tool_complexity_estimate",
        "tool_git_status", "tool_git_log", "tool_git_diff", "tool_git_compare_branches",
        "tool_detect_error_patterns",
        "tool_search_patterns", "tool_store_decision",
        "tool_create_task", "tool_report_status",
        "tool_diff_summary",
    },
    "bea-coder": {
        "tool_read_file", "tool_write_file", "tool_patch_file",
        "tool_list_directory", "tool_detect_file_dependencies",
        "tool_syntax_validate",
        "tool_git_branch_create", "tool_git_status", "tool_git_diff",
        "tool_git_commit", "tool_git_log",
        "tool_generate_diff", "tool_diff_summary",
        "tool_report_status", "tool_search_patterns",
    },
    "bea-reviewer": {
        "tool_read_file", "tool_list_directory", "tool_detect_file_dependencies",
        "tool_syntax_validate", "tool_import_graph", "tool_circular_import_detect",
        "tool_complexity_estimate",
        "tool_git_diff", "tool_git_log", "tool_git_status",
        "tool_git_compare_branches", "tool_git_detect_conflicts",
        "tool_generate_diff", "tool_diff_summary",
        "tool_detect_error_patterns", "tool_detect_regressions",
        "tool_report_status",
    },
    "bea-qa": {
        "tool_read_file", "tool_write_file", "tool_list_directory",
        "tool_syntax_validate",
        "tool_run_tests", "tool_run_single_test", "tool_detect_missing_tests",
        "tool_git_diff", "tool_git_status",
        "tool_detect_regressions",
        "tool_report_status",
    },
    "bea-devops": {
        "tool_read_file", "tool_list_directory",
        "tool_detect_docker_config", "tool_env_vars_check",
        "tool_python_version", "tool_detect_installed_packages",
        "tool_detect_missing_dependencies",
        "tool_git_status", "tool_git_log",
        "tool_run_tests",
        "tool_report_status",
    },
    "bea-watcher": {
        "tool_read_file", "tool_read_logs",
        "tool_detect_error_patterns", "tool_detect_regressions",
        "tool_git_status", "tool_git_log",
        "tool_run_tests",
        "tool_search_patterns", "tool_store_pattern",
        "tool_report_status",
    },
}

TOOL_CATALOG = [
    {"name": "git_branch_create", "purpose": "Create branch (bea/<agent>/<task>)", "risk": "supervised", "category": "git", "deps": ["git"]},
    {"name": "git_status", "purpose": "Get repo status", "risk": "safe", "category": "git", "deps": ["git"]},
    {"name": "git_diff", "purpose": "Generate diff against base branch", "risk": "safe", "category": "git", "deps": ["git"]},
    {"name": "git_log", "purpose": "View commit history", "risk": "safe", "category": "git", "deps": ["git"]},
    {"name": "git_commit", "purpose": "Stage and commit changes (never to master)", "risk": "supervised", "category": "git", "deps": ["git"]},
    {"name": "git_compare_branches", "purpose": "Compare two branches", "risk": "safe", "category": "git", "deps": ["git"]},
    {"name": "git_detect_conflicts", "purpose": "Check merge conflicts (dry-run)", "risk": "safe", "category": "git", "deps": ["git"]},
    {"name": "read_file", "purpose": "Read file content", "risk": "safe", "category": "filesystem", "deps": []},
    {"name": "write_file", "purpose": "Write file (protected files blocked)", "risk": "supervised", "category": "filesystem", "deps": []},
    {"name": "patch_file", "purpose": "Patch file with exact text replacement", "risk": "supervised", "category": "filesystem", "deps": []},
    {"name": "list_directory", "purpose": "List directory contents", "risk": "safe", "category": "filesystem", "deps": []},
    {"name": "detect_file_dependencies", "purpose": "Detect Python imports", "risk": "safe", "category": "filesystem", "deps": []},
    {"name": "syntax_validate", "purpose": "Validate Python syntax via ast.parse", "risk": "safe", "category": "analysis", "deps": []},
    {"name": "import_graph", "purpose": "Build import dependency graph", "risk": "safe", "category": "analysis", "deps": []},
    {"name": "circular_import_detect", "purpose": "Find circular import chains", "risk": "safe", "category": "analysis", "deps": []},
    {"name": "dead_code_detect", "purpose": "Find potentially unused code", "risk": "safe", "category": "analysis", "deps": []},
    {"name": "complexity_estimate", "purpose": "Estimate cyclomatic complexity", "risk": "safe", "category": "analysis", "deps": []},
    {"name": "run_tests", "purpose": "Run pytest suite", "risk": "safe", "category": "test", "deps": ["pytest"]},
    {"name": "run_single_test", "purpose": "Run a single test file", "risk": "safe", "category": "test", "deps": ["pytest"]},
    {"name": "detect_missing_tests", "purpose": "Find source files without tests", "risk": "safe", "category": "test", "deps": []},
    {"name": "generate_diff", "purpose": "Generate minimal diff", "risk": "safe", "category": "diff", "deps": ["git"]},
    {"name": "diff_summary", "purpose": "Structured diff summary", "risk": "safe", "category": "diff", "deps": ["git"]},
    {"name": "detect_regressions", "purpose": "Check changed files for syntax errors", "risk": "safe", "category": "diff", "deps": ["git"]},
    {"name": "read_logs", "purpose": "Read recent log entries", "risk": "safe", "category": "observability", "deps": []},
    {"name": "detect_error_patterns", "purpose": "Scan for bare except, print debug, TODOs", "risk": "safe", "category": "observability", "deps": []},
    {"name": "python_version", "purpose": "Detect Python version", "risk": "safe", "category": "environment", "deps": []},
    {"name": "detect_installed_packages", "purpose": "List installed packages", "risk": "safe", "category": "environment", "deps": []},
    {"name": "detect_missing_dependencies", "purpose": "Find missing imports", "risk": "safe", "category": "environment", "deps": []},
    {"name": "detect_docker_config", "purpose": "Inspect docker-compose files", "risk": "safe", "category": "environment", "deps": []},
    {"name": "env_vars_check", "purpose": "Check expected env vars (names only)", "risk": "safe", "category": "environment", "deps": []},
    {"name": "store_pattern", "purpose": "Store solution pattern with confidence", "risk": "supervised", "category": "knowledge", "deps": []},
    {"name": "search_patterns", "purpose": "Search past solution patterns", "risk": "safe", "category": "knowledge", "deps": []},
    {"name": "store_decision", "purpose": "Store architecture decision record", "risk": "supervised", "category": "knowledge", "deps": []},
    {"name": "create_task", "purpose": "Create structured task for an agent", "risk": "safe", "category": "coordination", "deps": []},
    {"name": "report_status", "purpose": "Report agent task status", "risk": "safe", "category": "coordination", "deps": []},
]
