"""
BeaMax P3.4 — GitHub Automation
Automates GitHub repository creation and code push for generated MVPs.
"""

import os
import subprocess  # nosec B404
import logging
from pathlib import Path
from typing import Dict, Any, Optional

from models.opportunity import Opportunity

logger = logging.getLogger(__name__)


class GitHubAutomation:
    """Automate GitHub repository creation and code push"""
    
    def __init__(self, github_token: Optional[str] = None, github_org: Optional[str] = None):
        """
        Initialize GitHub automation.
        
        Args:
            github_token: GitHub PAT (fallback to GH_TOKEN env)
            github_org: GitHub org (if not provided, creates in user account)
        """
        self.github_token = github_token or os.getenv("GH_TOKEN")
        self.github_org = github_org or os.getenv("GITHUB_ORG")
        
        if not self.github_token:
            logger.warning("github_token_missing - gh CLI may fail")
        
        logger.info(f"github_automation_initialized org={self.github_org}")
    
    def create_and_push(
        self,
        opportunity: Opportunity,
        mvp_dir: str,
        private: bool = True,
    ) -> Dict[str, Any]:
        """
        Create GitHub repo and push generated MVP code.
        
        Args:
            opportunity: Opportunity model
            mvp_dir: Path to generated MVP directory
            private: Create private repo (default: True)
        
        Returns:
            Dict with result:
            {
                "success": bool,
                "repo_url": str,
                "repo_name": str,
                "clone_url": str,
                "html_url": str,
                "message": str,
            }
        """
        mvp_path = Path(mvp_dir)
        if not mvp_path.exists():
            return {
                "success": False,
                "message": f"MVP directory not found: {mvp_dir}",
                "error": "directory_not_found",
            }
        
        repo_name = f"beamax-mvp-{opportunity.id}"
        
        logger.info(f"github_repo_creation_started opportunity_id={opportunity.id} repo={repo_name}")
        
        try:
            # 1. Create GitHub repo
            logger.debug(f"creating_github_repo name={repo_name} private={private}")
            
            create_cmd = [
                "gh", "repo", "create", repo_name,
                "--private" if private else "--public",
                "--description", f"{opportunity.title} - Generated by BeaMax",
            ]
            
            if self.github_org:
                create_cmd.insert(3, f"{self.github_org}/{repo_name}")
            
            result = subprocess.run(  # nosec B603 B607
                create_cmd,
                cwd=mvp_path,
                capture_output=True,
                text=True,
                timeout=30,
            )
            
            if result.returncode != 0:
                logger.error(f"github_repo_creation_failed: {result.stderr}")
                return {
                    "success": False,
                    "message": f"GitHub repo creation failed: {result.stderr}",
                    "error": "gh_create_failed",
                    "stderr": result.stderr,
                }
            
            logger.info(f"github_repo_created repo={repo_name}")
            
            # 2. Initialize git
            logger.debug("initializing_git_repo")
            subprocess.run(["git", "init"], cwd=mvp_path, check=True, capture_output=True)  # nosec B603 B607
            subprocess.run(["git", "add", "."], cwd=mvp_path, check=True, capture_output=True)  # nosec B603 B607
            subprocess.run(  # nosec B603 B607
                ["git", "commit", "-m", f"Initial commit - {opportunity.title}"],
                cwd=mvp_path,
                check=True,
                capture_output=True,
            )
            
            # 3. Add remote
            logger.debug("adding_git_remote")
            
            if self.github_org:
                remote_url = f"https://github.com/{self.github_org}/{repo_name}.git"
            else:
                # Get username from gh CLI
                whoami = subprocess.run(  # nosec B603 B607
                    ["gh", "api", "user", "--jq", ".login"],
                    capture_output=True,
                    text=True,
                    check=True,
                )
                username = whoami.stdout.strip()
                remote_url = f"https://github.com/{username}/{repo_name}.git"
            
            subprocess.run(  # nosec B603 B607
                ["git", "remote", "add", "origin", remote_url],
                cwd=mvp_path,
                check=True,
                capture_output=True,
            )
            
            # 4. Push code
            logger.debug("pushing_code_to_github")
            subprocess.run(  # nosec B603 B607
                ["git", "push", "-u", "origin", "main"],
                cwd=mvp_path,
                check=True,
                capture_output=True,
                timeout=60,
            )
            
            logger.info(f"github_push_completed repo={repo_name} url={remote_url}")
            
            # 5. Get repo info
            repo_info = subprocess.run(  # nosec B603 B607
                ["gh", "repo", "view", repo_name, "--json", "url,sshUrl,description"],
                cwd=mvp_path,
                capture_output=True,
                text=True,
                check=True,
            )
            
            import json
            repo_data = json.loads(repo_info.stdout)
            
            return {
                "success": True,
                "repo_name": repo_name,
                "repo_url": remote_url,
                "clone_url": repo_data.get("sshUrl", remote_url),
                "html_url": repo_data.get("url", remote_url),
                "message": f"GitHub repo created and code pushed: {repo_name}",
            }
        
        except subprocess.CalledProcessError as e:
            logger.error(f"github_automation_failed opportunity_id={opportunity.id}: {e}", exc_info=True)
            return {
                "success": False,
                "message": f"GitHub automation failed: {str(e)}",
                "error": "subprocess_failed",
                "stderr": getattr(e, "stderr", ""),
            }
        
        except Exception as e:
            logger.error(f"github_automation_exception opportunity_id={opportunity.id}: {e}", exc_info=True)
            return {
                "success": False,
                "message": f"GitHub automation exception: {str(e)}",
                "error": str(e),
            }
    
    def set_secrets(self, repo_name: str, secrets: Dict[str, str]) -> bool:
        """
        Set GitHub Actions secrets for the repo.
        
        Args:
            repo_name: Repository name (with org if applicable)
            secrets: Dict of secret name -> value
        
        Returns:
            bool: True if all secrets set successfully
        """
        logger.info(f"setting_github_secrets repo={repo_name} count={len(secrets)}")
        
        try:
            for key, value in secrets.items():
                logger.debug(f"setting_secret key={key}")
                
                result = subprocess.run(  # nosec B603 B607
                    ["gh", "secret", "set", key, "--repo", repo_name, "--body", value],
                    capture_output=True,
                    text=True,
                    timeout=15,
                )
                
                if result.returncode != 0:
                    logger.error(f"secret_set_failed key={key}: {result.stderr}")
                    return False
            
            logger.info(f"github_secrets_set repo={repo_name}")
            return True
        
        except Exception as e:
            logger.error(f"set_secrets_exception repo={repo_name}: {e}", exc_info=True)
            return False
