#requires -Version 5.1
<#
.SYNOPSIS
    Install the git pre-push hook that runs scripts/validate_local.ps1.

.DESCRIPTION
    Idempotent — safe to re-run; overwrites the existing hook if any.
    The hook fires on every `git push` and refuses the push if any local
    validation check fails. Skipped checks (e.g. pip-audit on non-ASCII
    Windows paths) don't block.

    Bypass once with `git push --no-verify`.

.EXAMPLE
    PS> .\scripts\install_pre_push_hook.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$HookFile = Join-Path $ProjectRoot ".git\hooks\pre-push"

if (-not (Test-Path (Join-Path $ProjectRoot ".git\hooks"))) {
    Write-Error "Not a git repo (no .git/hooks/). Run from inside the working tree."
    exit 1
}

$content = @'
#!/bin/sh
# Auto-generated by scripts/install_pre_push_hook.ps1
# Refuses the push if any local validation gate fails.
# Bypass once with: git push --no-verify
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(git rev-parse --show-toplevel)/scripts/validate_local.ps1"
'@

Set-Content -Path $HookFile -Value $content -Encoding ascii -NoNewline

Write-Host "Installed pre-push hook at: $HookFile" -ForegroundColor Green
Write-Host ""
Write-Host "Test it (without actually pushing):" -ForegroundColor Cyan
Write-Host "  git push --dry-run" -ForegroundColor White
Write-Host ""
Write-Host "Bypass once if needed:" -ForegroundColor Cyan
Write-Host "  git push --no-verify" -ForegroundColor White
